site_title: The Wandering Pharmacist
email: pharmadev@proton.me
description: My personal website
url: "https://CMagnac.github.io"
image_path: /assets/images
theme: minima
styles:
  - /assets/main.css
include: ["_tables"]